Update strip tags to actually strip tags
Expensify/expensify-common pull request #362
Opened 2021-04-15 22:02 UTC by yuwenmemon

@roryabraham will you please review this?
cc @tgolen

The way we were using `htmlDecode` in place of `stripHTML` was wrong I believe. Strip means to remove. In any case, the implementation of `htmlDecode` was not actually stripping tags in the first place:
```
>> Str.stripHTML('<strong>hello</strong>')
"<strong>hello</strong>"
>> $('<textarea/>').html('<strong>hello</strong>').text();
"<strong>hello</strong>"
```

### Fixed Issues
None, but using to clean up code mentioned here: https://github.com/Expensify/Expensify.cash/pull/2320/files#r613669999

# Tests
- Added Unit tests

2021-04-15 22:07 UTC, roryabraham reviewed
Did you look into how this function is used in Web-Expensify? I'm worried this is going to break stuff 😅

2021-04-15 22:07 UTC, roryabraham commented on __tests__/Str-test.js
> +    it('Correctly identifies valid urls', () => {
I think you'll want to rename this test

2021-04-16 00:44 UTC, deetergp reviewed
Other than the copypasta test description, this looks good to me.

2021-04-16 16:18 UTC, tgolen requested changes
Yeah, I agree that I am a bit worried that this could break other repos. Maybe we should add a new method instead and mark that one as deprecated? But first, let's check and see how often that method is used and where.

Would you mind cleaning up all the lint warnings? It looks like most of them are just lines that are too long.

2021-04-16 16:37 UTC, roryabraham commented
> Would you mind cleaning up all the lint warnings? It looks like most of them are just lines that are too long

These warnings have been here a while, but because they're all regex literals the lines can't really be broken up. Probably the best thing to do would be to just suppress them all I guess. (tempted to suggest we disable the max-length rule at the file level for that file).

2021-04-16 17:33 UTC, tgolen commented
Yep, I'm fine with suppressing some of them for things like regex
literals, though even regexes can be multi-line if you use the `x` (I
think) flag which ignores whitespace in the pattern. It looks like some
were just on comments though

On Fri, Apr 16, 2021 at 10:37 AM Rory Abraham ***@***.***>
wrote:

> Would you mind cleaning up all the lint warnings? It looks like most of
> them are just lines that are too long
>
> These warnings have been here a while, but because they're all regex
> literals the lines can't really be broken up. Probably the best thing to do
> would be to just suppress them all I guess. (tempted to suggest we disable
> the max-length rule at the file level for that file).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Expensify/expensify-common/pull/362#issuecomment-821298812>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJMAB37TBW4FJ4HJQ3FE3DTJBRUVANCNFSM43AKMKQA>
> .
>

2021-04-20 00:04 UTC, yuwenmemon commented
> But first, let's check and see how often that method is used and where.

Yeah, it's only used in two spots in Web-E. That's the only repo in which it's currently used:
```
yuwen@MemonbookProExpensify ~/Expensidev/Web-Expensify (yuwen-ghContributions) Web-Expensify % git grep stripHTML
site/app/dialogs/addCSV/addCSVView.jsx:                trans[i] = Str.stripHTML(row[layout[i]]);
site/app/dialogs/uploadCompanyCard/uploadCompanyCardView.jsx:                trans[fieldName] = Str.stripHTML(this.activeCSVObj[csvRowIndex][Number(fieldIndex)]).trim();
```

Checked out both those spots. They both meant to remove tags rather than escape them.

2021-04-20 00:04 UTC, yuwenmemon commented
I have read the CLA Document and I hereby sign the CLA

2021-04-20 06:22 UTC, yuwenmemon commented
Updated!

2021-04-20 14:33 UTC, tgolen approved these changes
Thanks for looking into that.

2021-04-20 16:44 UTC, roryabraham approved these changes
:nooice:

2021-04-20 16:44 UTC, merged