[WIP] Do not match empty markdown
Expensify/expensify-common pull request #443
Opened 2022-05-03 17:55 UTC by arosiclair

Updates regex and replace logic for code block, code fence and link markdown so that non-whitespace characters are required between the marks. This fixes an issue where 

### Fixed Issues
$ https://github.com/Expensify/App/issues/8720

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
1. What tests did you perform that validates your changed worked?

# QA
1. What does QA need to do to validate your changes?
1. What areas to they need to test for regressions?

2022-05-03 19:42 UTC, arosiclair commented
I have read the CLA Document and I hereby sign the CLA

2022-05-03 19:48 UTC, arosiclair commented
@alex-mechler ready for review when you are!

2022-05-03 22:30 UTC, alex-mechler reviewed
This solution doesnt seem to match what was discussed in the issue. Looking in the issue, it looks like we decided that we should not convert _empty_ codeblocks and fences. However, this will not convert anything that has no non-whitespace characters. if you send the following, shouldn't it be converted to a codeblock with a single empty line?
````
```

```
````

2022-05-04 14:09 UTC, arosiclair commented
Comments with only markup and whitespace also cause the issue in the GH (rejected by our API) so this change also doesn't match against whitespace-only to address that.

2022-05-04 21:04 UTC, alex-mechler requested changes

2022-05-04 21:04 UTC, alex-mechler commented on lib/ExpensiMark.js
> +                ,
Comma should be on the same line as the closing bracket

2022-05-05 15:25 UTC, alex-mechler approved these changes

2022-05-05 15:25 UTC, merged