[feat] Add formatting to markdown link text
Expensify/expensify-common pull request #446
Opened 2022-05-16 03:05 UTC by mdneyazahmad

@parasharrajat  will you please review this?

[Explanation of the change or anything fishy that is going on]

### Fixed Issues
$ https://github.com/Expensify/App/issues/8426

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
1. What tests did you perform that validates your changed worked?

# QA
1. What does QA need to do to validate your changes?
1. What areas to they need to test for regressions?

2022-05-16 03:06 UTC, mdneyazahmad commented
I have read the CLA Document and I hereby sign the CLA

2022-05-17 10:43 UTC, parasharrajat requested changes

2022-05-17 10:43 UTC, parasharrajat commented on lib/ExpensiMark.js
> +                // we are allowing only bold, strikethrough and italic formatting for link text
Comment can be improved. Mention why are we doing this. Comment starts from capitals.

2022-05-17 10:43 UTC, parasharrajat commented on lib/ExpensiMark.js
> +    replace(text, rules = []) {
```suggestion
    replace(text, filterRules = []) {
```
What rules? define the param in a comment.

2022-05-17 10:44 UTC, parasharrajat requested changes
Add more unit tests.

2022-05-23 02:39 UTC, mdneyazahmad commented
@parasharrajat updated

2022-05-23 17:16 UTC, mdneyazahmad commented on __tests__/ExpensiMark-Markdown-test.js
> +        + '[_italic_ ~strikethrough~ test.com](https://www.expensify-test.com) '
It passes this test. However the reverse is not producing the exact code.

---

`[https://www.text.com/_root_folder/1](https://www.text.com/_root_folder/1)` 
To
`<a href="https://www.text.com/_root_folder/1" target="_blank" rel="noreferrer noopener">https://www.text.com/_root_folder/1</a>`

---

`<a href="https://www.text.com/_root_folder/1" target="_blank">https://www.text.com/_root_folder/1</a>`
To
`https://www.text.com/_root_folder/1` and not `[https://www.text.com/_root_folder/1](https://www.text.com/_root_folder/1)` 

---

I think, it is fine. That is the same thing.

2022-05-23 18:05 UTC, mdneyazahmad commented
Updated

2022-05-26 13:28 UTC, MonilBhavsar approved these changes
Looks good to me!

2022-05-26 13:31 UTC, MonilBhavsar commented
In the related PR, in the QA section, let's add to test other markdown styles too

2022-05-26 13:34 UTC, merged

2022-05-26 13:40 UTC, MonilBhavsar commented
Feel free to update your other PR with commit hash `e989d858aa2ab8191284ae106acf9cd323ab879d`