Use default param and substring
Expensify/expensify-common pull request #459
Opened 2022-07-12 12:39 UTC by Beamanator

Found [here](https://github.com/Expensify/Expensify/issues/218385#issuecomment-1181677243) that we were getting an empty `eventID` passed in, causing an error that didn't allow merging receipts via the "Attach" paper clip icon

### Related Issues
$ Related to https://github.com/Expensify/Expensify/issues/218385

# Tests
1. Open a report
2. Add 2 very similar expenses
3. In the report, click "Details"
4. Click "Edit Expenses"
5. Edit one expense by clicking the pencil icon when hovering over an expense
6. Click "Merge" when looking at the expense
7. At this point you'll probably see a pretty empty dialog box (this error is being resolved in another PR)
8. Close the "Merge an expense" modal
9. Now you should see something like:
    - ![Screen Shot 2022-07-12 at 2 38 32 PM](https://user-images.githubusercontent.com/3885503/178491637-44d05b05-691c-4413-b06b-38681981f6b3.png)
10. Hover over this expense, click the Paper clip icon on the left
11. You should now be taken to "Merge Expenses" dialog:
    - ![Screen Shot 2022-07-12 at 2 39 02 PM](https://user-images.githubusercontent.com/3885503/178491704-755c41a3-9ebc-446f-9746-24bc50d277d0.png)

# QA
Same as above

2022-07-12 19:19 UTC, jasperhuangg commented
Tried testing this on my end and I'm getting stuck at step 10. Somehow when `eventID` is `null` it doesn't default to `''` apparently??

To test, I went into `node_modules` in `Web-Expensify` and changed `extractEventName` to this:

```
const extractEventName = (eventID = '') => {
    console.log(">>>> eventID=", eventID);
    return eventID.substring(0, eventID.indexOf('@#@'));
}
```

Then, this happens:

https://user-images.githubusercontent.com/31285285/178575855-eec2b10a-f593-4ebc-a4f2-b1b2a7d54996.mov

Once `expensify-common` is minified, it appears that it has converted the function into this:

```
var extractEventName = function extractEventName() {
  var eventID = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : '';
  console.log(">>>> eventID=", eventID);
  return eventID.substring(0, eventID.indexOf('@#@'));
};
```

If `arguments[0]` is `null`, then the ternary assignment of `eventID` isn't gonna default to `''`. 

@Beamanator Am I missing something here?

2022-07-12 19:20 UTC, jasperhuangg requested changes
See above

2022-07-13 13:54 UTC, Beamanator commented
Innnnteresting! So what I did was:
1. Change `extractEventName` to `const extractEventName = (eventID = '') => eventID.substring(0, eventID.indexOf('@#@'));` in `node_modules/expensify-common/lib/PubSub.jsx`
2. Ran grunt watch
3. Did the above test steps.

When I did that flow it seemed to work for me:

https://user-images.githubusercontent.com/3885503/178750756-aaf63d4b-0f32-492b-8d60-08c0453894b4.mov

Did you do something different?

2022-07-14 18:42 UTC, jasperhuangg commented
> Innnnteresting! So what I did was:
> 
> 1. Change `extractEventName` to `const extractEventName = (eventID = '') => eventID.substring(0, eventID.indexOf('@#@'));` in `node_modules/expensify-common/lib/PubSub.jsx`
> 2. Ran grunt watch
> 3. Did the above test steps.
> 
> When I did that flow it seemed to work for me:
> 
>  Screen.Recording.2022-07-13.at.3.54.01.PM.mov 
> Did you do something different? I wonder if you just needed to run grunt watch after making the node modules change?

that's exactly what I did too, but I just tried it again tho and it worked. gonna go ahead and merge, sorry for the confusion

2022-07-14 18:43 UTC, merged

2022-07-15 08:07 UTC, Beamanator commented
haha what the heck! so weird 🤷