Remove Subscription Change Options
Expensify/expensify-common pull request #493
Opened 2023-01-31 21:18 UTC by Luke9389

### Fixed Issues
$ https://github.com/Expensify/Expensify/issues/259131

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
1. What tests did you perform that validates your changed worked?

# QA
1. What does QA need to do to validate your changes?
1. What areas to they need to test for regressions?

2023-02-01 07:17 UTC, MariaHCD requested changes
Wasn't able to comment on the unchanged lines but the prompts need to be updated for all these options as per the issue :)

2023-02-01 07:17 UTC, MariaHCD commented on lib/CONST.jsx
>          },
```suggestion
        BUSINESS_CLOSING: {
            id: 'businessClosing',
            label: 'Company closing, downsizing, or acquired',
            prompt: 'Would you have liked to continue using Expensify, or would you recommend it in your network?',
        },
```

2023-02-01 07:17 UTC, MariaHCD commented on lib/CONST.jsx
>              prompt: 'What software are you migrating to and what led to this decision?',
```suggestion
            prompt: 'What about our customer support didn\'t work well for you?',
```

2023-02-01 20:35 UTC, Luke9389 commented
Oh I missed that. Thanks @MariaHCD

2023-02-02 08:27 UTC, MariaHCD approved these changes
LGTM!

[Expensify - Settings - Policies.webm](https://user-images.githubusercontent.com/12268372/216271037-052ee3d0-2518-4abe-b92a-93b07fb17e0c.webm)

2023-02-02 08:27 UTC, merged

2023-02-02 12:36 UTC, flaviadefaria commented
Shoot I'm sorry I added the correct copy in one place but not in the other this is the correct copy:

id: 'tooLimited' - update prompt to "What software are you migrating to and what led to this decision?"
id: 'tooExpensive' - update prompt to "What software are you migrating to and what do you think is a fair price?"
id: 'inadequateSupport', - update prompt to "What software are you migrating to and what led to this decision?"
id: 'businessClosing' - update prompt to "What software are you migrating to and what led to this decision?"

Basically the prompt should be the same in all cases.

2023-02-02 12:46 UTC, MariaHCD commented
Ah, whoops. @flaviadefaria, so to clarify all the prompts should be `What software are you migrating to and what led to this decision?`?

2023-02-02 12:55 UTC, MariaHCD commented
Created a PR fix here: https://github.com/Expensify/expensify-common/pull/495

2023-02-02 13:08 UTC, flaviadefaria commented
Thanks @MariaHCD! Also `TOO_LIMITED` should have the label shortened to 'Functionality needs improvement'