Fixes italic markdown to match newline and adds tests
Expensify/expensify-common pull request #501
Opened 2023-02-15 01:34 UTC by alexxxwork

Markdown symbols like `*text*`, `~text~` or `_text_` should match text with newlines.
Bold and strikethrough markdown have been fixed here https://github.com/Expensify/expensify-common/pull/486
this PR adds fix for italic text `_text_` and corresponding tests
@neil-marcellini @eVoloshchak please take a look.

### Fixed Issues
$ https://github.com/Expensify/App/issues/14675

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
```
npm test -- __tests__/ExpensiMark-HTML-test.js
```
```
npm test -- __tests__/ExpensiMark-Markdown-test.js
```
1. What tests did you perform that validates your changed worked?
tested on native and web
<details>
<summary>ios</summary>
<img width="432" alt="Screenshot 2023-02-15 06 05 23" src="https://user-images.githubusercontent.com/3872759/218899007-b9460695-d1d2-4f69-aa81-e2bd75b3f919.png">
</details>
<details>
<summary>ios web</summary>
<img width="430" alt="Screenshot 2023-02-15 06 14 25" src="https://user-images.githubusercontent.com/3872759/218900160-6645774e-af9c-4a69-b60b-cddee9746d2c.png">
</details>
<details>
<summary>android</summary>
<img width="385" alt="Screenshot 2023-02-15 06 33 40" src="https://user-images.githubusercontent.com/3872759/218904769-4555dc78-e5be-4a01-b323-858f07a59ea5.png">

</details>
<details>
<summary>android web</summary>
<img width="385" alt="Screenshot 2023-02-15 06 29 41" src="https://user-images.githubusercontent.com/3872759/218902728-531b2dc1-ffc3-4711-af76-5b8cf81bf479.png">
</details>
<details>
<summary>web</summary>
<img width="509" alt="Screenshot 2023-02-15 06 10 41" src="https://user-images.githubusercontent.com/3872759/218899415-278e9cae-95e7-4cee-957d-a3dbb365f7a5.png">
</details>

# QA
1. What does QA need to do to validate your changes?
Changes should be validated in App
1. What areas to they need to test for regressions?
Markdown italic in composer

2023-02-15 01:35 UTC, alexxxwork commented
I have read the CLA Document and I hereby sign the CLA

2023-02-15 17:27 UTC, eVoloshchak requested changes

2023-02-15 17:27 UTC, eVoloshchak commented on lib/ExpensiMark.js
> +            // Use [\s\S]* instead of .* to match newline
```suggestion
            
            // Use [\s\S]* instead of .* to match newline
```

2023-02-15 17:31 UTC, eVoloshchak commented
> I think as long as they comment on it you can assign them as a reviewer

✅

2023-02-15 19:08 UTC, eVoloshchak submitted a review, later dismissed
Tests well!

2023-02-15 19:16 UTC, neil-marcellini approved these changes
Great! The code looks good and it tests well. Thank you.

2023-02-15 19:21 UTC, neil-marcellini requested changes
@alexxxwork Looks like you have a lint error. While you're at it, would you please move the multi-line italic tests directly below the single line italic test? That's how I've organized things so far.

2023-02-16 18:58 UTC, alexxxwork commented
> @alexxxwork Looks like you have a lint error. While you're at it, would you please move the multi-line italic tests directly below the single line italic test? That's how I've organized things so far.

It's a bug in a fix :) Fixed!

2023-02-16 19:00 UTC, neil-marcellini commented
> would you please move the multi-line italic tests directly below the single line italic test?

@alexxxwork

2023-02-16 19:02 UTC, alexxxwork commented
> > would you please move the multi-line italic tests directly below the single line italic test?
> 
> @alexxxwork

Sorry, missed it! Just a moment

2023-02-16 19:13 UTC, alexxxwork commented
@neil-marcellini All fixed!

2023-02-16 19:17 UTC, eVoloshchak commented
There is still something weird with access to the repository, I can't see the lint check, only those 3
<img width="501" alt="image" src="https://user-images.githubusercontent.com/9059945/219465191-244716d6-1745-4084-9aad-fdb8c7a89777.png">

Local tests are looking good

2023-02-16 19:17 UTC, eVoloshchak submitted a review, later dismissed

2023-02-16 22:37 UTC, neil-marcellini approved these changes
👍

2023-02-16 22:40 UTC, neil-marcellini commented
Now it says that the commits need to be signed. I didn't think we required this for contributors so I'll ask in Slack.

2023-02-16 22:51 UTC, neil-marcellini commented
@alexxxwork It looks like we do ask you to sign your commits in the contributing guidelines [here](https://github.com/Expensify/App/blob/1d83fe14bfcf0f7078ee4ae23ad9e89c50167677/contributingGuides/CONTRIBUTING.md?plain=1#L127-L129).

Once you have set up commit signing you can follow these instructions to sign the commits by rebasing and force pushing to this branch.

1. Check out a new branch to test on in case you mess up

2. Find the commit before the ones you want to change

3. `git rebase -i --preserve-merges <sha>`

4. Change `pick` to `edit` for the commits you want to sign

5. `git commit -S --amend --no-edit` when it prompts you

6. `git rebase --continue`

7. Push your new branch to github, confirm that it is fixed

8. Repeat steps 3-6 on your actual branch and force push.

2023-02-17 03:24 UTC, alexxxwork commented
@neil-marcellini thank you very much for such a detailed instruction. It seems that I just commited from another PC without my gpg key. 
Meanwhile, found more 'automatic' way for such cases: `git rebase --exec 'git commit --amend --no-edit -n -S' -i <hash of the commit to rebase to>`

2023-02-17 18:55 UTC, neil-marcellini approved these changes
Good to go. Thanks for signing the commits and posting a quicker method! I'll post that to our internal documentation.

2023-02-17 19:05 UTC, merged