Remove `[block]` intermediary
Expensify/expensify-common pull request #541
Opened 2023-05-23 14:06 UTC by tienifr

### Fixed Issues

# Tests

1. Login with any account
2. Go to any chat
3. Type the word `[block]` and send it
4. Click the pencil icon to edit the comment
5. Verify that the composer shows `[block]` as is

# QA

2023-05-23 17:39 UTC, PauloGasparSv commented
Assigning @cead22 and @rushatgabhane from the original issue here!

2023-05-23 23:02 UTC, cead22 requested changes
Just one small change. We should test that every piece of markdown we support is working correctly, but maybe those tests can go in the App PR, and we can get a full contributor checklist going in there as well

2023-05-24 00:15 UTC, cead22 commented
It's only a suggestion. We don't have to merge this PR in order to put the tests in the App PR, we can update the commit hash of expensify-common in package.json in app and test there, and once we're happy with the tests, we can merge this PR and update the commit hash again in the App PR.

The thing is we don't have the reviewer checklist here, but as long as we test sending and editing every type of markdown we support as part of the tests, that works for me

2023-05-24 02:40 UTC, tienifr commented
Thanks! I will create another PR for regression testing. It'll be up really soon.

2023-05-24 05:26 UTC, tienifr commented
The App PR is up here: https://github.com/Expensify/App/pull/19511.

2023-05-24 05:27 UTC, tienifr commented on lib/ExpensiMark.js
>      replaceBlockWithNewLine(htmlString) {
`replaceBlockElementWithNewLine` sounds better to me.

2023-05-24 19:02 UTC, cead22 commented
>replaceBlockElementWithNewLine sounds better to me.

👍

2023-05-26 19:51 UTC, cead22 submitted a review, later dismissed

2023-05-29 18:09 UTC, cead22 commented
@tienifr can you rebase the merge commit so it's signed so we can merge without changing the branch protection restrictions?

2023-05-30 20:58 UTC, cead22 approved these changes

2023-05-30 20:58 UTC, merged