fix: parsing mention wrapped with styles inside link text
Expensify/expensify-common pull request #549
Opened 2023-06-14 11:33 UTC by eh2077

### Fixed Issues
$ https://github.com/Expensify/App/issues/19997

# Tests
1. Go to a chat and add a comment 
```
[_@username@expensify.com_](expensify.com)
```
2. Verify that the text `@username@expensify.com` of link is not rendered as mention and is italic 

# QA
Same as test

2023-06-14 12:36 UTC, s77rt requested changes

2023-06-14 12:36 UTC, s77rt commented on __tests__/ExpensiMark-HTML-test.js
> +test('Test for mention inside link and wrapped by styles like italic, bold, strikethrough or code', () => {
Can you add tests for email as well e.g. `[_@username@expensify.com_](username@expensify.com)`

Also we have `Test for user mention inside link markdown` and `Test for user mention inside email markdown` tests, maybe we can merge those here.

2023-06-14 17:20 UTC, s77rt approved these changes
LGTM! :rocket: 

cc @luacmartins

2023-06-14 17:30 UTC, luacmartins approved these changes
LGTM

2023-06-14 17:31 UTC, merged

2023-06-15 16:55 UTC, johnmlee101 commented
Wasn't I suppose to be assigned?

2023-06-15 19:12 UTC, luacmartins commented
I think so, not sure why Melvin assigned me instead 🤔

2023-06-15 20:46 UTC, s77rt commented
I think auto assignment never worked correctly cross repos.