first commit
Expensify/expensify-common pull request #569
Opened 2023-08-31 06:23 UTC by akamefi202

Update strikethrough replace rule to fix multiple tilde error

### Fixed Issues
https://github.com/Expensify/App/issues/25693

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
In ExpensiMark-HTML-test.js file, test named "Test strikethrough with multiple tilde characters" works correctly. 
2. What tests did you perform that validates your changed worked?
Checked if the updated strikethrough rule only wraps content inside tilde characters.

# QA
1. What does QA need to do to validate your changes?
Run the new test cases.
3. What areas to they need to test for regressions?
N/A

2023-08-31 09:06 UTC, akamefi202 commented on package-lock.json
Done

2023-08-31 09:21 UTC, akamefi202 commented
@parasharrajat I updated the PR title and description.

2023-08-31 17:50 UTC, neil-marcellini requested changes
I think we should also test html to text and html to markdown to make sure that all works too.

I don't really understand the full regex, so let's be sure to also test the steps from [the PR](https://github.com/Expensify/expensify-common/pull/461) where this was last changed.

2023-08-31 17:50 UTC, neil-marcellini commented on __tests__/ExpensiMark-HTML-test.js
> +
NAB: Remove spaces on blank line

2023-08-31 18:11 UTC, akamefi202 commented on __tests__/ExpensiMark-HTML-test.js
> +    expect(parser.replace(testString)).toBe('~~~~~~');
Okay

2023-08-31 23:42 UTC, tylerkaraszewski approved these changes

2023-09-01 21:40 UTC, neil-marcellini approved these changes

2023-09-04 05:33 UTC, akamefi202 commented
@tylerkaraszewski @parasharrajat @neil-marcellini Can we merge this PR if it is approved?

2023-09-11 15:24 UTC, merged