End the url at the first unmatched closing parenthesis
Expensify/expensify-common pull request #578
Opened 2023-09-19 15:31 UTC by ShogunFire

@robertKozik @cead22 
We end the url at the first unmatched parenthesis because it is unlikely that this closing parenthesis is part of the url and it can be part of the markdown for example

### Fixed Issues
$ https://github.com/Expensify/App/issues/26788

# Tests
1. Go to any report
2. Send a link with multiple umatched closing parentheses that are not all at the end, for example: `google.com/(toto))titi)`
3. Verify that the link ends at the first unmatched parenthesis, in the above example the link should be `google.com/(toto)`

# QA
Same tests and test urls and markdown in general

# Video

https://github.com/Expensify/expensify-common/assets/19537677/ff78206c-b5c6-41b3-b519-558eea3a6037

2023-09-19 15:39 UTC, ShogunFire commented
@robertKozik

2023-09-20 03:43 UTC, neil-marcellini commented
@cead22 I'm going to let you take this one since you're the assigned engineer on the issue.

2023-09-22 04:55 UTC, cead22 requested changes

2023-09-22 04:55 UTC, cead22 commented on lib/ExpensiMark.js
> +                    if(unmatchedOpenParentheses <= 0){ // unmatched closing parenthesis
Comment should be above the code line, and the first letter capitalized
```suggestion
                    // We found an unmatched closing parenthesis
                    if(unmatchedOpenParentheses <= 0){ 
```

2023-09-25 15:14 UTC, ShogunFire commented
@cead22 I made the changes

2023-09-26 00:42 UTC, cead22 submitted a review, later dismissed

2023-09-26 01:23 UTC, cead22 commented
@ShogunFire lint errors

2023-09-26 11:52 UTC, ShogunFire commented
They should be fixed now but I can't verify because it doesn't launch the test

2023-09-28 09:49 UTC, cead22 approved these changes

2023-09-28 09:49 UTC, merged