Issue-26016 make usermention case insensitive
Expensify/expensify-common pull request #591
Opened 2023-10-25 05:48 UTC by nikhildewoolkar

### Fixed Issues
[$ GH_LINK](https://github.com/Expensify/App/issues/26016)
https://github.com/Expensify/App/issues/26016

# Tests
Open the app
Open any report
Write '@' to trigger mentions
Select any one mention, make any letter of mention as capital and send
Hover on mention to observe that tooltip doesn't display the right display name and avatar
For same mention as step 4 or select different mention and capitalize all letters and send
Observe that now it is not displayed as mention

2023-10-30 17:33 UTC, neil-marcellini commented
@sobitneupane would you please comment here so I can assign you for review? @nikhildewoolkar please link the fixed issue properly next time so that auto assignment runs.

2023-10-30 18:38 UTC, neil-marcellini requested changes

2023-10-30 18:38 UTC, neil-marcellini commented on __tests__/ExpensiMark-HTML-test.js
> +    expect(parser.replace('<mention-user>@user@DOMAIN.com</mention-user>')).toBe(testString);
This file is for testing markdown to html, not the other way around. Let's remove these tests and keep them in the proper file.

2023-10-30 18:38 UTC, neil-marcellini commented on __tests__/ExpensiMark-HTMLToText-test.js
> +    expect(parser.replace('<mention-user>@user@DOMAIN.com</mention-user>')).toBe(testString);
Use `parser.htmlToText`

2023-10-30 18:38 UTC, neil-marcellini commented on __tests__/ExpensiMark-HTMLToText-test.js
> +    expect(parser.replace(testString)).toBe('<mention-user>@user@domain.com</mention-user>');
Remove these tests since this file is for testing html to text.

2023-10-30 18:38 UTC, neil-marcellini commented on __tests__/ExpensiMark-Markdown-test.js
> +    expect(parser.replace('<mention-user>@user@DOMAIN.com</mention-user>')).toBe(testString);
Only test htmlToMarkdown with that method

2023-11-01 06:34 UTC, sobitneupane reviewed
@nikhildewoolkar 
We do have test for user mention in "ExpensiMark-HTML-test.js"
https://github.com/Expensify/expensify-common/blob/82bfcd1cb077afd03d1c8c069618c7dd5bd405d8/__tests__/ExpensiMark-HTML-test.js#L1103-L1107

You can add other similar tests with capital letters in username and domain.


We do not have tests for html to text for `<mention-user>` as of now. You can add those tests in "/ExpensiMark-HTMLToText-test.js" file. Please go through existing tests in the file and add new tests accordingly.

2023-11-02 14:53 UTC, nikhildewoolkar commented
Kindly review PR. I have made requested changes.

2023-11-02 19:15 UTC, neil-marcellini approved these changes
Woohoo 🎉

2023-11-03 12:22 UTC, sobitneupane approved these changes
Changes look good and tests well.

cc: @neil-marcellini

2023-11-03 17:30 UTC, merged