Allow indented text in quotes
Expensify/expensify-common pull request #673
Opened 2024-03-28 19:05 UTC by tienifr

This PR enables indented text to show as is (do not trim the spaces) in quotes.

### Fixed Issues
$ https://github.com/Expensify/App/issues/38156

# Tests
**1. What unit/integration tests cover your change? What autoQA tests cover your change?**

The `ExpensiMark-HTML-test.js` is updated to include the new test cases and modify existing tests to match with new expected behaviors.

**2. What tests did you perform that validates your changed worked?**

- Run the unit test.
- Test in Expensify App follow these steps:

1. Send a quote message with indentation:

```
> No indent
>     Indented 4
```

2. Verify the `Indented 4` line shows with 4-space indentation in quote

# QA
**1. What does QA need to do to validate your changes?**

Test in Expensify App follow these steps:

1. Send a quote message with indentation:

```
> No indent
>     Indented 4
```

2. Verify the `Indented 4` line shows with 4-space indentation in quote

**2. What areas to they need to test for regressions?**

# Screenshots

https://github.com/Expensify/expensify-common/assets/113963320/beb8e130-03e0-487d-932e-ddef9952ebb5

2024-03-28 22:12 UTC, s77rt commented
Inconsistency, send the following message:
```
> k
>>       hi         
>       hi there        
> k
```

Notice that there are spaces after both hi and hi there. But when the message is sent we are trimming the spaces only on the nested quote (the hi message)

<img width="625" alt="Screenshot 2024-03-28 at 11 11 57 PM" src="https://github.com/Expensify/expensify-common/assets/16493223/7483b4cc-4b8e-4af8-a798-d7b41fdafdba">
.

2024-03-29 17:27 UTC, s77rt commented
@tienifr I don't have a strong preference, as long as we have consistency it should be good enough. Perhaps 2️⃣ is a better fit here

2024-03-30 23:33 UTC, s77rt commented
@tienifr Any progress on this?

2024-04-01 12:17 UTC, s77rt requested changes

2024-04-02 08:23 UTC, Julesssss commented
> So we still keep both trailing and leading spaces, right?

@s77rt from your conversation above this sounds the best option. Can you please confirm so we can finish up this PR. Thanks

2024-04-02 11:10 UTC, s77rt commented
Yes, we won't alter user input on quotes

2024-04-02 11:14 UTC, s77rt requested changes

2024-04-02 11:14 UTC, s77rt commented on __tests__/ExpensiMark-HTML-test.js
> +    expect(parser.replace(testString)).toBe('<blockquote>quote </blockquote><h1>heading 1 after the quote.</h1>Here is a multi-line<br />comment that contains <strong>bold</strong> string.');
Where is that extra space coming from? Does not seem this is a wanted space

2024-04-02 14:42 UTC, s77rt commented on __tests__/ExpensiMark-HTML-test.js
> +    expect(parser.replace(testString)).toBe('<blockquote>quote </blockquote><h1>heading 1 after the quote.</h1>Here is a multi-line<br />comment that contains <strong>bold</strong> string.');
I was reading something different 😅 My bad. Looks good

2024-04-02 14:42 UTC, s77rt approved these changes

2024-04-02 14:44 UTC, s77rt commented
cc @Julesssss

2024-04-02 15:35 UTC, Julesssss approved these changes

2024-04-02 15:35 UTC, Julesssss commented
Testing to occur when the `common` library is bumped in App

2024-04-02 15:35 UTC, merged