ExpensiMark: Add New Markdown Truncation Utility
Expensify/expensify-common pull request #675
Opened 2024-04-01 16:41 UTC by brandonhenry

### Fixed Issues
$ https://github.com/Expensify/App/issues/37357

# Tests
1. What unit/integration tests cover your change? What autoQA tests cover your change?
2. What tests did you perform that validates your changed worked?

https://github.com/Expensify/expensify-common/blob/7c88b3ff10f92ab044fae7b4bac838b6d37fa1f0/__tests__/ExpensiMark-Markdown-Truncate-test.js

2024-04-04 07:32 UTC, NikkiWines requested changes
some very minor stylistic requests

2024-04-04 07:32 UTC, NikkiWines commented on lib/ExpensiMark.js
> +const HYPERLINK = /^\[([^[]+)\]\(([^)]+)\)/;
Some more consistent whitespace: 

```suggestion
const ASTERISK_ITALIC_PLACEHOLDER_REGEXP = /ASTERISKITALICPLACEHOLDER/gm;

const ESCAPED_ASTERISK_REGEXP = /\\\*/g;
const ESCAPED_UNDERSCORE_REGEXP = /\\_/g;
const UNDERSCORE_BOLD_REGEXP = /(__)(.*?)(__)/g;
const ASTERISK_BOLD_REGEXP = /(\*\*)(.*?)(\*\*)/g;
const UNDERSCORE_ITALIC_REGEXP = /(_)(.*?)(_)/g;
const ASTERISK_ITALIC_REGEXP = /(\*)(.*?)(\*)/g;
const HYPERLINK = /^\[([^[]+)\]\(([^)]+)\)/;
```

2024-04-04 07:32 UTC, NikkiWines commented on lib/ExpensiMark.js
> +
```suggestion
```

2024-04-04 07:32 UTC, NikkiWines commented on lib/ExpensiMark.js
> +
```suggestion
```

2024-04-04 15:38 UTC, puneetlath commented
cc @shubham1206agra as C+

2024-04-23 13:39 UTC, NikkiWines commented
@brandonhenry you've got conflicts 

@shubham1206agra can you please review ASAP? Thank you

2024-04-30 13:26 UTC, puneetlath commented
Have you reviewed yet @shubham1206agra?

2024-06-11 04:43 UTC, NikkiWines requested changes
Looks good so far, couple of questiosn mainly on the tests.

2024-06-11 04:43 UTC, NikkiWines commented on __tests__/ExpensiMark-Markdown-Truncate-test.js
> +        const html = 'This is a text with <blockquote>code block</blockquote> that exceeds the limit. The code block should be preserved in the truncated text. Here is an example code block:\n\n```ja
Not sure of the purpose of the `<blockquote>` tag as part of this test and the current text is long enough that the code block is not preserved. 
```suggestion
        const html = 'This is a text with code block that exceeds the limit. The code block should be preserved in the truncated text. Here is an example code block:\n\n```javascript\nconsole.log("Hello, world!");\n```\n\nThe truncation should handle code blocks correctly.';
```

2024-06-11 04:43 UTC, NikkiWines commented on __tests__/ExpensiMark-Markdown-Truncate-test.js
> +        expect(result).toBe('This is a text with lists that exceeds the limit. The lists should be preserved in the truncated tex...');
Same thing here, the text is too long to actually test the intended condition

2024-06-11 04:43 UTC, NikkiWines commented on __tests__/ExpensiMark-Markdown-Truncate-test.js
> +        expect(result).toBe('This is a text with horizontal rules that exceeds the limit. The horizontal rules should be preserve...');
Same here

2024-06-11 04:43 UTC, NikkiWines commented on lib/ExpensiMark.js
> +            const defaultPos = maxLength - totalLength;
We prefer non-abbreviated variable names when possible

2024-06-11 04:43 UTC, NikkiWines commented on lib/ExpensiMark.js
> +        function getEndPosition(content, tailPos) {
NAB: But it might be nice to add some comments to this function since it's a little dense as is.

2024-06-25 03:42 UTC, NikkiWines commented
Will take a look at this first thing tomorrow, sorry for the delay

2024-06-26 22:20 UTC, NikkiWines requested changes
Couple small things

2024-06-26 22:20 UTC, NikkiWines commented on lib/ExpensiMark.ts
> +
NAB: 
```suggestion
```

2024-07-03 12:04 UTC, NikkiWines requested changes
Couple more comments on the tests but looks pretty good

2024-07-03 12:04 UTC, NikkiWines commented on __tests__/ExpensiMark-Markdown-Truncate-test.js
> +            'This is a *long* text that exceeds the character limit. It contains multiple sentences to test the truncation functionality. The truncation should occur at the nearest space to avoid cut
This blurb doesn't match the expected result, since we truncate mid-word with ellipses, not at the nearest space

2024-07-03 12:04 UTC, NikkiWines commented on __tests__/ExpensiMark-Markdown-Truncate-test.js
> +    });
Same thing for this test - we're not truncating at a space even though that's apparently the expected behavior

2024-07-03 12:04 UTC, NikkiWines commented on __tests__/ExpensiMark-Markdown-Truncate-test.js
> +        const markdown = 'This is a text with lists. Here is an example of a list:\n\n- Item 1\n- Item 2\n- Item 3\n\nThe truncation should handle lists correctly.';
Technically this isn't a list, right? Just a series of newlines? Should we be using `-` or a numbered list in the test here?

2024-07-03 19:48 UTC, NikkiWines requested changes
One last comment, looks good otherwise!

2024-07-03 19:48 UTC, NikkiWines commented on __tests__/ExpensiMark-Markdown-Truncate-test.js
> +            'This is a *long* text that exceeds the character limit. It contains multiple sentences to test the truncation functionality. The truncation should occur at the nearest space to avoid cut
Can we update this copy then since it's incorrect? I know the test title is correct but it's good to be consistent still

2024-07-08 13:45 UTC, NikkiWines requested changes
I see just a few more misleading test values but otherwise looks good

2024-07-08 13:45 UTC, NikkiWines commented on __tests__/ExpensiMark-Markdown-Truncate-test.js
> +        const markdown = 'This is a *long _nested_ markdown* text. It contains *_bold italic_* and ~_strikethrough italic_~ formatting. The truncation should handle the nesting correctly.';
There's no truncation involved in this text.

2024-07-08 13:45 UTC, NikkiWines commented on __tests__/ExpensiMark-Markdown-Truncate-test.js
> +        const markdown = 'This is a text with `inline code`. The inline code should be preserved in the truncated text.';
Same for this one

2024-07-09 15:41 UTC, NikkiWines commented
Sorry to hear that @brandonhenry, take your time!!! Hope things are alright and services are restored soon 🍀

2024-07-15 14:25 UTC, NikkiWines approved these changes
:shipit: looks good!

2024-07-15 15:43 UTC, puneetlath approved these changes

2024-07-15 15:43 UTC, merged