Use new logic to check bold text
Expensify/expensify-common pull request #710
Opened 2024-05-30 12:08 UTC by ShridharGoel

Use new logic to check bold text: https://github.com/Expensify/App/issues/41109#issuecomment-2095057640

### Fixed Issues
$ https://github.com/Expensify/App/issues/41109

Tests and QA steps:

1. Type anything on a Google document.
2. Copy it.
3. Paste it in Expensify.
4. Check if the font is still normal (it shouldn't be bold).
5. Now, type something in bold text on a Google document.
6. Copy/paste to Expensify.
7. It should show in bold.

https://github.com/Expensify/expensify-common/assets/35566748/86e457a4-919a-46af-b261-8d9565763be8

https://github.com/Expensify/expensify-common/assets/35566748/3c22cbc6-c51e-42b3-b318-f918907035aa

2024-05-30 19:14 UTC, jasperhuangg requested changes
Please show testing steps and screenshots of this change working with the App PR you're going to submit.

Please also link the App PR in the description.

JS Linter is also failing, try running `npm run prettier`

2024-06-03 17:09 UTC, jasperhuangg commented
Hey @ShridharGoel any updates on this?

2024-06-07 17:30 UTC, jasperhuangg commented
@ShridharGoel Please prioritize this when you can

2024-06-10 16:58 UTC, jasperhuangg submitted a review, later dismissed

2024-06-10 17:00 UTC, jasperhuangg commented
@ShridharGoel the tests are failing, please fix them.

For the linter tests, just run `npm run prettier` and commit the changes.

Please find the failing JS tests here: https://github.com/Expensify/expensify-common/actions/runs/9379944077/job/25851454328?pr=710

2024-06-13 19:13 UTC, jasperhuangg commented
Bump @ShridharGoel

2024-06-14 16:48 UTC, jasperhuangg commented
@ShridharGoel Did you run `npm run prettier` locally? I just ran it and there's still a diff, all you need to do is run it and commit the difference. I can't do so because I'm a reviewer.

```
╰─ git diff
diff --git a/lib/ExpensiMark.js b/lib/ExpensiMark.js
index 2c51e80..917606f 100644
--- a/lib/ExpensiMark.js
+++ b/lib/ExpensiMark.js
@@ -411,9 +411,8 @@ export default class ExpensiMark {
                 replacement: (match, tagContent, innerContent) => {
                     const fontWeightMatch = innerContent.match(/style="(.*?)"/);
                     const isFontWeightBold = fontWeightMatch
-                    ? fontWeightMatch[1].replaceAll(/\s/g, "").includes("font-weight:bold;") ||
-                      fontWeightMatch[1].replaceAll(/\s/g, "").includes("font-weight:700;")
-                    : false;
+                        ? fontWeightMatch[1].replaceAll(/\s/g, '').includes('font-weight:bold;') || fontWeightMatch[1].replaceAll(/\s/g, '').includes('font-weight:700;')
+                        : false;
                     const isBold = fontWeightMatch ? isFontWeightBold : true;
                     return isBold ? `*${innerContent}*` : innerContent;
                 },
```

2024-06-14 19:41 UTC, jasperhuangg commented
@ShridharGoel Still have linter errors, why aren't you running `npm run prettier`? Either do that or just correctly apply the diff that I'm showing you 😆 

```
╰─ git diff
diff --git a/lib/ExpensiMark.js b/lib/ExpensiMark.js
index fd54708..917606f 100644
--- a/lib/ExpensiMark.js
+++ b/lib/ExpensiMark.js
@@ -411,7 +411,7 @@ export default class ExpensiMark {
                 replacement: (match, tagContent, innerContent) => {
                     const fontWeightMatch = innerContent.match(/style="(.*?)"/);
                     const isFontWeightBold = fontWeightMatch
-                        ? fontWeightMatch[1].replaceAll(/\s/g, "").includes("font-weight:bold;") || fontWeightMatch[1].replaceAll(/\s/g, "").includes("font-weight:700;")
+                        ? fontWeightMatch[1].replaceAll(/\s/g, '').includes('font-weight:bold;') || fontWeightMatch[1].replaceAll(/\s/g, '').includes('font-weight:700;')
                         : false;
                     const isBold = fontWeightMatch ? isFontWeightBold : true;
                     return isBold ? `*${innerContent}*` : innerContent
```

2024-06-17 18:33 UTC, jasperhuangg submitted a review, later dismissed

2024-06-17 18:37 UTC, jasperhuangg commented
@ShridharGoel it looks like your commits aren't signed, can you look into this?

```
The base branch requires all commits to be signed
```

2024-06-18 10:37 UTC, alitoshmatov commented on lib/ExpensiMark.js
> +                    const isBold = fontWeightMatch ? isFontWeightBold : true;
Can you add comments to explain what's happening it became pretty unclear what's going on.

2024-06-18 10:40 UTC, alitoshmatov commented
I think we also need unit tests to cover this cases

2024-06-20 18:32 UTC, jasperhuangg commented
@ShridharGoel bump!

2024-06-20 18:34 UTC, jasperhuangg commented
Gonna go ahead and stick this back on draft while the unit tests are worked out.

2024-06-23 20:25 UTC, alitoshmatov commented
Thank you @jasperhuangg looks like we need to revisit our solution on this one. @ShridharGoel Can have a look at this https://github.com/Expensify/App/issues/41109#issuecomment-2178227233

2024-06-26 21:33 UTC, jasperhuangg commented
@ShridharGoel Do you mind also updating your screenshots to handle the new cases outlined in https://github.com/Expensify/App/issues/41109#issuecomment-2178227233

2024-07-03 19:04 UTC, jasperhuangg approved these changes
LGTM @alitoshmatov all yours

2024-07-06 20:32 UTC, alitoshmatov approved these changes
Looks good to me to, I think we can merge this.

2024-07-08 18:29 UTC, merged