Unify the blockquote parsing logic for messages and rawInput
Expensify/expensify-common pull request #820
Opened 2024-11-18 09:03 UTC by Skalakid

This PR changes and unifies the blockquote parsing logic for the NewDot messages and the Live Markdown Input. Currently, the parsing result is different when the `shouldKeepRawInput` variable is `true`. Thanks to the changes in this PR, the results are consistent (visually). The only difference is that the tags are being grouped when `shouldKeepRawInput=false`.

Example:
```
> test
>> test
> test
``` 

NewDot sent message `shouldKeepRawInput=false`
```
<blockquote>test<br /><blockquote>test</blockquote>test</blockquote>
```

Live Markdown Input `shouldKeepRawInput=true`
```
<blockquote> test</blockquote>
<blockquote><blockquote> test</blockquote></blockquote>
<blockquote> test</blockquote>
```

### Fixed Issues
https://github.com/Expensify/App/issues/45154
https://github.com/Expensify/App/issues/47951

# Tests
1. Applying changes to both the NewDot app and the Live Markdown Input
2. Verify if the markdown is the same when writing the message and after sending it

# QA
Same as Tests

2024-11-28 12:35 UTC, Pujan92 commented
commenting for the assignment.

2024-12-02 09:06 UTC, Skalakid commented
Hi @pecanoro, can you assign @Pujan92 to review this PR please?

2024-12-02 16:34 UTC, pecanoro commented
Hmm for some reason I can't add him tot he issue even if he commented

2024-12-02 16:50 UTC, pecanoro requested changes

2024-12-04 09:41 UTC, Skalakid commented on lib/ExpensiMark.ts
> +    replaceQuoteText(text: string, shouldKeepRawInput: boolean): {replacedText: string; shouldAddSpace: boolean} {
Done!

2024-12-04 13:32 UTC, Pujan92 commented
@Skalakid I am trying to link this commit in E/App but facing some issue while running the app. Wondering how you connected and tested in E/App?

2024-12-04 21:08 UTC, Skalakid commented
@Pujan92 expensify-common commits can't be linked to the E/App, but you can add my changes by running `npm i` and then `npm run  build` in the expensify-common repo. After this, copy the JS code from the `/dist/ExpensifyMark.js` file into the `/node_modules/expensify-common/dist/ExpensiMark.js` file in NeeDot

2024-12-05 10:37 UTC, Pujan92 commented
@Skalakid Isn't the message here should be the same as of live markdown input(Applied a space between 2 blockquotes)?

https://github.com/user-attachments/assets/c7cba1d1-3c3b-4f99-b1f1-14d4a6d474f6

2024-12-05 14:57 UTC, Skalakid commented
@Pujan92 Oh, I forgot to tell you one more detail to set up the testing environment, sorry 😅 You must also apply these ExpensiMark changes inside the Live Markdown Library. To do that, you have to:
1. Clone react-native-live-markdown repo
2. Go to the `@Skalakid/fix-blockquote-formatting` branch. I've updated and committed changes for ExpensiMarkd inside Live Markdown parser 
3. Run `yarn install` 
4. `yarn prepare`
5. `yarn pack` - it will generate a packed Live Markdown library file that you can install in the NewDot App
6. Go to the NewDot repo, and in the console, run `npm i -S <path_to_the_previously_generated_tgz_file>`
8. Run `npm i`

And now you will have new parsing logic applied both in the NewDot and Live Markdown libraries :D

2024-12-05 14:59 UTC, Skalakid commented
Also, it's worth mentioning here that new rules for the blockquote has been discussed here and now this "> > >" won't be parsed as a nested blocquote

2024-12-05 15:05 UTC, Skalakid commented
I updated the PR description with new rules explanation

2024-12-05 16:04 UTC, pecanoro approved these changes

2024-12-05 16:05 UTC, pecanoro commented
@Pujan92 I can't assign you for review to this PR but let me know when you have tested it and you can just leave a LGTM and I will merge it!

2024-12-05 17:33 UTC, Pujan92 approved these changes
LGTM, Thanks @Skalakid!

2024-12-05 18:34 UTC, merged